// flow-typed signature: 4359dea1ace4ead024a2ff6b8c52cf0c
// flow-typed version: <<STUB>>/@types/node_v^15.0.2/flow_v0.150.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
