// flow-typed signature: 0fe8b3140b451996ef0b94b84d4be830
// flow-typed version: <<STUB>>/ava_v^3.11.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ava'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ava' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ava/cli' {
  declare module.exports: any;
}

declare module 'ava/eslint-plugin-helper' {
  declare module.exports: any;
}

declare module 'ava/lib/api' {
  declare module.exports: any;
}

declare module 'ava/lib/assert' {
  declare module.exports: any;
}

declare module 'ava/lib/chalk' {
  declare module.exports: any;
}

declare module 'ava/lib/cli' {
  declare module.exports: any;
}

declare module 'ava/lib/code-excerpt' {
  declare module.exports: any;
}

declare module 'ava/lib/concordance-options' {
  declare module.exports: any;
}

declare module 'ava/lib/context-ref' {
  declare module.exports: any;
}

declare module 'ava/lib/create-chain' {
  declare module.exports: any;
}

declare module 'ava/lib/environment-variables' {
  declare module.exports: any;
}

declare module 'ava/lib/extensions' {
  declare module.exports: any;
}

declare module 'ava/lib/fork' {
  declare module.exports: any;
}

declare module 'ava/lib/globs' {
  declare module.exports: any;
}

declare module 'ava/lib/is-ci' {
  declare module.exports: any;
}

declare module 'ava/lib/like-selector' {
  declare module.exports: any;
}

declare module 'ava/lib/line-numbers' {
  declare module.exports: any;
}

declare module 'ava/lib/load-config' {
  declare module.exports: any;
}

declare module 'ava/lib/node-arguments' {
  declare module.exports: any;
}

declare module 'ava/lib/now-and-timers' {
  declare module.exports: any;
}

declare module 'ava/lib/parse-test-args' {
  declare module.exports: any;
}

declare module 'ava/lib/provider-manager' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/beautify-stack' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/colors' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/default' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/format-serialized-error' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/improper-usage-messages' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/prefix-title' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/tap' {
  declare module.exports: any;
}

declare module 'ava/lib/run-status' {
  declare module.exports: any;
}

declare module 'ava/lib/runner' {
  declare module.exports: any;
}

declare module 'ava/lib/serialize-error' {
  declare module.exports: any;
}

declare module 'ava/lib/snapshot-manager' {
  declare module.exports: any;
}

declare module 'ava/lib/test' {
  declare module.exports: any;
}

declare module 'ava/lib/watcher' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/dependency-tracker' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/ensure-forked' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/ipc' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/line-numbers' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/main' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/options' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/subprocess' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ava/cli.js' {
  declare module.exports: $Exports<'ava/cli'>;
}
declare module 'ava/eslint-plugin-helper.js' {
  declare module.exports: $Exports<'ava/eslint-plugin-helper'>;
}
declare module 'ava/index' {
  declare module.exports: $Exports<'ava'>;
}
declare module 'ava/index.js' {
  declare module.exports: $Exports<'ava'>;
}
declare module 'ava/lib/api.js' {
  declare module.exports: $Exports<'ava/lib/api'>;
}
declare module 'ava/lib/assert.js' {
  declare module.exports: $Exports<'ava/lib/assert'>;
}
declare module 'ava/lib/chalk.js' {
  declare module.exports: $Exports<'ava/lib/chalk'>;
}
declare module 'ava/lib/cli.js' {
  declare module.exports: $Exports<'ava/lib/cli'>;
}
declare module 'ava/lib/code-excerpt.js' {
  declare module.exports: $Exports<'ava/lib/code-excerpt'>;
}
declare module 'ava/lib/concordance-options.js' {
  declare module.exports: $Exports<'ava/lib/concordance-options'>;
}
declare module 'ava/lib/context-ref.js' {
  declare module.exports: $Exports<'ava/lib/context-ref'>;
}
declare module 'ava/lib/create-chain.js' {
  declare module.exports: $Exports<'ava/lib/create-chain'>;
}
declare module 'ava/lib/environment-variables.js' {
  declare module.exports: $Exports<'ava/lib/environment-variables'>;
}
declare module 'ava/lib/extensions.js' {
  declare module.exports: $Exports<'ava/lib/extensions'>;
}
declare module 'ava/lib/fork.js' {
  declare module.exports: $Exports<'ava/lib/fork'>;
}
declare module 'ava/lib/globs.js' {
  declare module.exports: $Exports<'ava/lib/globs'>;
}
declare module 'ava/lib/is-ci.js' {
  declare module.exports: $Exports<'ava/lib/is-ci'>;
}
declare module 'ava/lib/like-selector.js' {
  declare module.exports: $Exports<'ava/lib/like-selector'>;
}
declare module 'ava/lib/line-numbers.js' {
  declare module.exports: $Exports<'ava/lib/line-numbers'>;
}
declare module 'ava/lib/load-config.js' {
  declare module.exports: $Exports<'ava/lib/load-config'>;
}
declare module 'ava/lib/node-arguments.js' {
  declare module.exports: $Exports<'ava/lib/node-arguments'>;
}
declare module 'ava/lib/now-and-timers.js' {
  declare module.exports: $Exports<'ava/lib/now-and-timers'>;
}
declare module 'ava/lib/parse-test-args.js' {
  declare module.exports: $Exports<'ava/lib/parse-test-args'>;
}
declare module 'ava/lib/provider-manager.js' {
  declare module.exports: $Exports<'ava/lib/provider-manager'>;
}
declare module 'ava/lib/reporters/beautify-stack.js' {
  declare module.exports: $Exports<'ava/lib/reporters/beautify-stack'>;
}
declare module 'ava/lib/reporters/colors.js' {
  declare module.exports: $Exports<'ava/lib/reporters/colors'>;
}
declare module 'ava/lib/reporters/default.js' {
  declare module.exports: $Exports<'ava/lib/reporters/default'>;
}
declare module 'ava/lib/reporters/format-serialized-error.js' {
  declare module.exports: $Exports<'ava/lib/reporters/format-serialized-error'>;
}
declare module 'ava/lib/reporters/improper-usage-messages.js' {
  declare module.exports: $Exports<'ava/lib/reporters/improper-usage-messages'>;
}
declare module 'ava/lib/reporters/prefix-title.js' {
  declare module.exports: $Exports<'ava/lib/reporters/prefix-title'>;
}
declare module 'ava/lib/reporters/tap.js' {
  declare module.exports: $Exports<'ava/lib/reporters/tap'>;
}
declare module 'ava/lib/run-status.js' {
  declare module.exports: $Exports<'ava/lib/run-status'>;
}
declare module 'ava/lib/runner.js' {
  declare module.exports: $Exports<'ava/lib/runner'>;
}
declare module 'ava/lib/serialize-error.js' {
  declare module.exports: $Exports<'ava/lib/serialize-error'>;
}
declare module 'ava/lib/snapshot-manager.js' {
  declare module.exports: $Exports<'ava/lib/snapshot-manager'>;
}
declare module 'ava/lib/test.js' {
  declare module.exports: $Exports<'ava/lib/test'>;
}
declare module 'ava/lib/watcher.js' {
  declare module.exports: $Exports<'ava/lib/watcher'>;
}
declare module 'ava/lib/worker/dependency-tracker.js' {
  declare module.exports: $Exports<'ava/lib/worker/dependency-tracker'>;
}
declare module 'ava/lib/worker/ensure-forked.js' {
  declare module.exports: $Exports<'ava/lib/worker/ensure-forked'>;
}
declare module 'ava/lib/worker/ipc.js' {
  declare module.exports: $Exports<'ava/lib/worker/ipc'>;
}
declare module 'ava/lib/worker/line-numbers.js' {
  declare module.exports: $Exports<'ava/lib/worker/line-numbers'>;
}
declare module 'ava/lib/worker/main.js' {
  declare module.exports: $Exports<'ava/lib/worker/main'>;
}
declare module 'ava/lib/worker/options.js' {
  declare module.exports: $Exports<'ava/lib/worker/options'>;
}
declare module 'ava/lib/worker/subprocess.js' {
  declare module.exports: $Exports<'ava/lib/worker/subprocess'>;
}
