// flow-typed signature: a5b5b7986c2a475f07f7257aaea18fa7
// flow-typed version: <<STUB>>/c8_v^7.9.0/flow_v0.159.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'c8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'c8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'c8/bin/c8' {
  declare module.exports: any;
}

declare module 'c8/lib/commands/check-coverage' {
  declare module.exports: any;
}

declare module 'c8/lib/commands/report' {
  declare module.exports: any;
}

declare module 'c8/lib/is-cjs-esm-bridge' {
  declare module.exports: any;
}

declare module 'c8/lib/parse-args' {
  declare module.exports: any;
}

declare module 'c8/lib/report' {
  declare module.exports: any;
}

declare module 'c8/lib/source-map-from-file' {
  declare module.exports: any;
}

// Filename aliases
declare module 'c8/bin/c8.js' {
  declare module.exports: $Exports<'c8/bin/c8'>;
}
declare module 'c8/index' {
  declare module.exports: $Exports<'c8'>;
}
declare module 'c8/index.js' {
  declare module.exports: $Exports<'c8'>;
}
declare module 'c8/lib/commands/check-coverage.js' {
  declare module.exports: $Exports<'c8/lib/commands/check-coverage'>;
}
declare module 'c8/lib/commands/report.js' {
  declare module.exports: $Exports<'c8/lib/commands/report'>;
}
declare module 'c8/lib/is-cjs-esm-bridge.js' {
  declare module.exports: $Exports<'c8/lib/is-cjs-esm-bridge'>;
}
declare module 'c8/lib/parse-args.js' {
  declare module.exports: $Exports<'c8/lib/parse-args'>;
}
declare module 'c8/lib/report.js' {
  declare module.exports: $Exports<'c8/lib/report'>;
}
declare module 'c8/lib/source-map-from-file.js' {
  declare module.exports: $Exports<'c8/lib/source-map-from-file'>;
}
