// flow-typed signature: 10479bcb4adfbf1c4e7f2630cb15c55b
// flow-typed version: <<STUB>>/tsd_v^0.17.0/flow_v0.159.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tsd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tsd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tsd/dist/cli' {
  declare module.exports: any;
}

declare module 'tsd/dist' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/assert' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers/assignability' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers/expect-deprecated' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers/handler' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers/identicality' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers/informational' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions/handlers/strict-assertion' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/assertions' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/compiler' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/config' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/formatter' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/interfaces' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/parser' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/rules/files-property' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/rules' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/rules/types-property' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/utils/get-json-property-position' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/utils/make-diagnostic' {
  declare module.exports: any;
}

declare module 'tsd/dist/lib/utils/typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tsd/dist/cli.js' {
  declare module.exports: $Exports<'tsd/dist/cli'>;
}
declare module 'tsd/dist/index' {
  declare module.exports: $Exports<'tsd/dist'>;
}
declare module 'tsd/dist/index.js' {
  declare module.exports: $Exports<'tsd/dist'>;
}
declare module 'tsd/dist/lib/assertions/assert.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/assert'>;
}
declare module 'tsd/dist/lib/assertions/handlers/assignability.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers/assignability'>;
}
declare module 'tsd/dist/lib/assertions/handlers/expect-deprecated.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers/expect-deprecated'>;
}
declare module 'tsd/dist/lib/assertions/handlers/handler.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers/handler'>;
}
declare module 'tsd/dist/lib/assertions/handlers/identicality.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers/identicality'>;
}
declare module 'tsd/dist/lib/assertions/handlers/index' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers'>;
}
declare module 'tsd/dist/lib/assertions/handlers/index.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers'>;
}
declare module 'tsd/dist/lib/assertions/handlers/informational.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers/informational'>;
}
declare module 'tsd/dist/lib/assertions/handlers/strict-assertion.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions/handlers/strict-assertion'>;
}
declare module 'tsd/dist/lib/assertions/index' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions'>;
}
declare module 'tsd/dist/lib/assertions/index.js' {
  declare module.exports: $Exports<'tsd/dist/lib/assertions'>;
}
declare module 'tsd/dist/lib/compiler.js' {
  declare module.exports: $Exports<'tsd/dist/lib/compiler'>;
}
declare module 'tsd/dist/lib/config.js' {
  declare module.exports: $Exports<'tsd/dist/lib/config'>;
}
declare module 'tsd/dist/lib/formatter.js' {
  declare module.exports: $Exports<'tsd/dist/lib/formatter'>;
}
declare module 'tsd/dist/lib/index' {
  declare module.exports: $Exports<'tsd/dist/lib'>;
}
declare module 'tsd/dist/lib/index.js' {
  declare module.exports: $Exports<'tsd/dist/lib'>;
}
declare module 'tsd/dist/lib/interfaces.js' {
  declare module.exports: $Exports<'tsd/dist/lib/interfaces'>;
}
declare module 'tsd/dist/lib/parser.js' {
  declare module.exports: $Exports<'tsd/dist/lib/parser'>;
}
declare module 'tsd/dist/lib/rules/files-property.js' {
  declare module.exports: $Exports<'tsd/dist/lib/rules/files-property'>;
}
declare module 'tsd/dist/lib/rules/index' {
  declare module.exports: $Exports<'tsd/dist/lib/rules'>;
}
declare module 'tsd/dist/lib/rules/index.js' {
  declare module.exports: $Exports<'tsd/dist/lib/rules'>;
}
declare module 'tsd/dist/lib/rules/types-property.js' {
  declare module.exports: $Exports<'tsd/dist/lib/rules/types-property'>;
}
declare module 'tsd/dist/lib/utils/get-json-property-position.js' {
  declare module.exports: $Exports<'tsd/dist/lib/utils/get-json-property-position'>;
}
declare module 'tsd/dist/lib/utils/index' {
  declare module.exports: $Exports<'tsd/dist/lib/utils'>;
}
declare module 'tsd/dist/lib/utils/index.js' {
  declare module.exports: $Exports<'tsd/dist/lib/utils'>;
}
declare module 'tsd/dist/lib/utils/make-diagnostic.js' {
  declare module.exports: $Exports<'tsd/dist/lib/utils/make-diagnostic'>;
}
declare module 'tsd/dist/lib/utils/typescript.js' {
  declare module.exports: $Exports<'tsd/dist/lib/utils/typescript'>;
}
