// flow-typed signature: fa03bac30d5cd30d6d6b91bed817be0c
// flow-typed version: <<STUB>>/xo_v^0.29.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xo/cli-main' {
  declare module.exports: any;
}

declare module 'xo/cli' {
  declare module.exports: any;
}

declare module 'xo/config/overrides' {
  declare module.exports: any;
}

declare module 'xo/config/plugins' {
  declare module.exports: any;
}

declare module 'xo/lib/constants' {
  declare module.exports: any;
}

declare module 'xo/lib/open-report' {
  declare module.exports: any;
}

declare module 'xo/lib/options-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xo/cli-main.js' {
  declare module.exports: $Exports<'xo/cli-main'>;
}
declare module 'xo/cli.js' {
  declare module.exports: $Exports<'xo/cli'>;
}
declare module 'xo/config/overrides.js' {
  declare module.exports: $Exports<'xo/config/overrides'>;
}
declare module 'xo/config/plugins.js' {
  declare module.exports: $Exports<'xo/config/plugins'>;
}
declare module 'xo/index' {
  declare module.exports: $Exports<'xo'>;
}
declare module 'xo/index.js' {
  declare module.exports: $Exports<'xo'>;
}
declare module 'xo/lib/constants.js' {
  declare module.exports: $Exports<'xo/lib/constants'>;
}
declare module 'xo/lib/open-report.js' {
  declare module.exports: $Exports<'xo/lib/open-report'>;
}
declare module 'xo/lib/options-manager.js' {
  declare module.exports: $Exports<'xo/lib/options-manager'>;
}
